require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - lib/generators/iaq_gen/templates/**
    - bin/**

RSpec/DescribedClass:
  Exclude:
    - spec/helpers/**
    - spec/lib_modules/**

Metrics/LineLength:
  Max: 500

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false