require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**

Metrics/LineLength:
  Max: 400

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false