backup:
  storage:
    username:       'abc'
    password:       'abc'
    ip:             'localhost'
    port:           22
  notifier:
    address:        'smtp.gmail.com'
    port:           '587'
    domain:         'gmail.com'
    username:       'abc@gmail.com'
    password:       'abc'

development:
   address:               'smtp.gmail.com'
   port:                  '587'
   domain:                'gmail.com'
   user_name:             'abc@gmail.com'
   password:              'abc'
   authentication:        'plain'

showcase:
   address:               'smtp.gmail.com'
   port:                  '587'
   domain:                'gmail.com'
   user_name:             'florian@sirius.com'
   password:              'abc'
   authentication:        'plain'

test:
    address:              'smtp.mail.yahoo.com.br'
    port:                 '465'
    domain:               'mail.yahoo.com'
    user_name:            'abc'
    password:             'abc'
    authentication:       'plain'

production:
    address:              'smtp.mail.yahoo.com.br'
    port:                 '465'
    domain:               'mail.yahoo.com'
    user_name:            'abc'
    password:             'abc'
    authentication:       'plain'

prod_secret: fc22ee10c89c1a350cb54ea14089ee39234da7210f5cc629205c35abdf7e8d16fe6bcc5f878d5b2b76edc0993df14fe7e09d3cea3929a768f44dea773f564782
